### ISSUE TITLE
Tutorial fails due to missing .dot file

### ISSUE THREAD

**Issue by fredRos** [mkarbach/gammacombo#13]
Following the tutorial section in the manual, even the first command that should compute something fails

```sh
$ bin/tutorial -c 1 -i --var a_gaus --ps 1
...
Graphviz::openFile() : ERROR : Could not open file. plots/dot/circle_tutorial1.dot
```
I suppose this file should be created first? It is not part of the source distribution.

**Comment by mkarbach** [comment]
Hi Fred,

Weird, will have to check tomorrow. At this point it tries to write the file- maybe the directory plots/dot didn't get created?

Cheers
Moritz

**Comment by matthewkenzie** [comment]
Hi Fred,

I'm just trying to debug your problem. Are you running on linux? Both Moritz and I are Mac users so it's a little difficult to debug as this problem does not seem to occur on mac.

The missing file should get made the line before the error:

https://github.com/mkarbach/gammacombo/blob/master/core/src/Graphviz.cpp#L42

- Can you confirm that the directory plots/dot exists?
- Can you also confirm there is no warning or error from of stream that the file plots/dot/circle_tutorial1.dot could not be opened?
- Maybe it is enough to add to L42 of core/src/Graphviz.cpp:

dotfile->open(name, std::ofstream::out)

Let me know if you still have problems and I will try the build on a linux platform to see if I can find the problem.

Cheers,

Matt

**Comment by fredRos** [comment]
Hello Matthew,

yes I'm running under linux and this seems to make the difference. You have to ensure that subdirectories exist before you can create a file in there. I can fix the example this way:
```sh
$ mkdir -p plots/dot
$ bin/tutorial -c 1 -i --var a_gaus --ps 1
```
Note that I use `-p` in  `mkdir -p` so any nonexisting subdirectories are automatically created. Seems like on Mac OS  this is the default but on linux it's the other way around. Check this
http://stackoverflow.com/questions/675039/how-can-i-create-directory-tree-in-c-linux
on how to deal with it in C++. Since you use boost anyways, presumably the most convenient way is http://stackoverflow.com/a/675095/987623

**Comment by matthewkenzie** [comment]
Hi Fred,

I think Moritz and I may have found the problem which is related to a mistake in the README. There is a missing " cd .." in the README.

After you do make install you need to cd ../tutorial and then run bin/tutorial from there.

Does this make a difference?

Matt

**Comment by fredRos** [comment]
Yes. Now it works when I follow exactly the steps in `readme.md`.

I actually I had two build directories, `build-root5` and `build-root6`. Your instructions require that the build directory actually be called `build`. I'm not sure if that's how it's done in the cmake world but I'd expect you let the user decide the name and figure out the build directory instead of hardcoding it. In addition, I was expecting to install gammacombo into another directory than the root of the checkout but that again doesn't work with your setup. You might want to consider allowing more flexibility for the advanced user in your installation process. To integrate well with other software, you'd want to install to `$PREFIX/lib`, `$PREFIX/bin/`, `$PREFIX/include`. Then it is much easier to dynamically (un)load your software as a module.
