### ISSUE TITLE
tutorial typos

### ISSUE THREAD

**Issue by rknegjens** [mkarbach/gammacombo#16]
Just read through the tutorial in the user manual (22-3-2015), nicely pedagogical, thanks:)
I noted some minor typos:

Step 1: should be
```
cp tutorial/cartesian .
```
and
```
rm -r cartesian/cartesian # delete the solution!
```

Step 10: (very minor...) error message should be setCorrelations not initCorrelations

Step 12: third bullet point: "include/" -> "src/"

**Comment by mkarbach** [comment]
Hi Rob, thanks! All fixed. Moritz
